### ISSUE TITLE
Latest Follower

### ISSUE THREAD

**Issue by ic3dr460n** [dlive-apis/dlivetv-api-js#11]
getChannel Followers seems to be working however I was wanting to get the latest follower and it seems when using when using first on list it pulls the same one. Is there another feature that could be added to support this? 

It would be good to have the same support for currency and subscribers too.

**Comment by Carbowix** [comment]
There's a event system that provides you with an update when someone follows the initialized channel however. Same thing goes to the gifts etc.getChannelFollowers gets your the whole list of followers with a limit specified. Getting subscribers isn't possible currently because there's no way to view subscribers in a channel. Only way is by being the owner of the channel.
